### ISSUE TITLE
Release for Foxy

### ISSUE THREAD

**Issue by jacobperron** [ros-tooling/libstatistics_collector#13]
## Description

We're doing our first round of releases into the ROS Foxy distro and this package should also be tagged and released.

Currently, we are blocked by dependencies being released, specifically `rcl` and `rcpputils`. I can provide updates on the release status of those packages, but you can expect them to be released soon (today).

**Comment by prajakta-gokhale** [comment]
Thanks for the heads up! We'll be on the lookout and release this package when possible to do so.

**Comment by emersonknapp** [comment]
rcpputils is released

**Comment by jacobperron** [comment]
It took longer than I expected, but we are now released up to `rcl`. I think `libstatistics_collector` can be released now.

**Comment by dabonnie** [comment]
> It took longer than I expected, but we are now released up to `rcl`. I think `libstatistics_collector` can be released now.

Thanks for the update! We'll get started on this and contact you when finished.

**Comment by jacobperron** [comment]
https://github.com/ros/rosdistro/pull/24647

Thank you!

**Comment by jacobperron** [comment]
We should cut new release for the Foxy Release Candidate (scheduled for tomorrow). This will ensure the debs have the latest changes. If someone from the tooling WG could do this that would be appreciated. I'm re-opening this issue for tracking.

**Comment by jacobperron** [comment]
@dabonnie FYI

**Comment by dabonnie** [comment]
Hey @jacobperron: I can rebloom the package if needed. Is this meant to capture all of the documentation additions? Just curious why as I believe we have not made any code changes.

**Comment by jacobperron** [comment]
Changes to the code were introduced in https://github.com/ros-tooling/libstatistics_collector/pull/18/

**Comment by dabonnie** [comment]
@jacobperron opened https://github.com/ros/rosdistro/pull/25122

**Comment by jacobperron** [comment]
In order for bloom to pick up the latest changes, we need a new tag (i.e. version number).

Before running bloom, we should add a new git tag (bumping the version). We typically update the changelog (e.g. https://github.com/ros-tooling/libstatistics_collector/commit/bf51ff4800df2cec128f52fe3771865d9a6582e7 ) and make a new commit bumping the version which we git tag (e.g. https://github.com/ros-tooling/libstatistics_collector/commit/6010227fcce4ae9a34ac4c3e6bdaf201fd6e789b).
We have some tools that can help with this process, `catkin_generate_changelog` and `catkin_prepare_release`. See this wiki page for more info: http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease

**Comment by jacobperron** [comment]
@dabonnie Thanks!
