### ISSUE TITLE
Request for 1.4.0 release for Humble

### ISSUE THREAD

**Issue by Timple** [ros-tooling/libstatistics_collector#152]
## Description

Today I was bitten again by https://github.com/ros-tooling/libstatistics_collector/issues/51 which is solved in https://github.com/ros-tooling/libstatistics_collector/pull/54. Can a new buildfarm released be triggered for Humble such that it uses version 1.4.0?

## Related Issues

https://github.com/ros-tooling/libstatistics_collector/issues/51

## Completion Criteria

Bloom release

**Comment by Timple** [comment]
Here you go: #153

**Comment by christophebedard** [comment]
#153 was merged and included in version 1.3.1, which is available: https://repo.ros2.org/status_page/ros_humble_default.html?q=libstatistics_collector

Closing.
