### ISSUE TITLE
Change type of received_message

### ISSUE THREAD

**Issue by CursedRock17** [ros-tooling/libstatistics_collector#168]
## Description
The point of this issue is to highlight discussion to change from a type `T` to `message_info` in the `OnMessageReceived` Function. I would be able to make a pull request for these changes, if the `libstatistics_collector` library wanted to go along with this

## Related Issues
This was discussed in pull request [2247](https://github.com/ros2/rclcpp/pull/2274) over in the `rclcpp` library. If you want to follow discussion up to this point, it has all happened there.

## Completion Criteria

  - Must change type `T` in `const T & received_message` within all `OnMessageReceived` functions to either `rmw_message_info_t` or if we wanted to import rclcpp (which we probably don't) `clcpp::MessageInfo`
  - Then deprecate all `OnMessageReceived` functions that are templated with type `T`

## Testing Notes / Suggestions

Not much other than changing the message types passed to the test functions.

**Comment by clalancette** [comment]
>     * Must change type `T` in `const T & received_message` within all `OnMessageReceived` functions to either `rmw_message_info_t` or if we wanted to import rclcpp (which we probably don't) `clcpp::MessageInfo`

Agreed that we can't take a new dependency on `rclcpp` here.  That would lead to a circular dependency that would be hard to undo.  This package already depends on `rcl`, which in turn depends on `rmw`, so it is OK to take an explicit dependency on it for this feature.

**Comment by MichaelOrlov** [comment]
@CursedRock17 Sounds good :+1:

**Comment by CursedRock17** [comment]
Sounds good, it's been checked off as ready to go and all the uncrustify errors are fixed so once it's reviewed and the CI is ran on it, I'll change up rclcpp message handling.

**Comment by fujitatomoya** [comment]
@CursedRock17 i totally missed this one, i will take a look.
