### ISSUE TITLE
Build Error 

### ISSUE THREAD

**Issue by pdl0x0lbq** [ros-tooling/libstatistics_collector#171]
## Description
An error occurred when I was compiling libstatistics_collector.

### Expected Behavior
Compilation successful

### Actual Behavior
`CMake Error at /home/sw/ros2_android_ws/install/rosidl_cmake/share/rosidl_cmake/cmake/rosidl_target_interfaces.cmake:47 (message):
  rosidl_target_interfaces() the second argument 'libstatistics_collector'
  concatenated with the third argument 'rosidl_typesupport_c' using double
  underscores must be a valid target name
Call Stack (most recent call first):
  /home/sw/ros2_android_ws/install/rosidl_generator_java/share/rosidl_generator_java/cmake/rosidl_generator_java_generate_interfaces.cmake:259 (rosidl_target_interfaces)
  /home/sw/ros2_android_ws/install/ament_cmake_core/share/ament_cmake_core/cmake/core/ament_execute_extensions.cmake:48 (include)
  /home/sw/ros2_android_ws/install/rosidl_cmake/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:286 (ament_execute_extensions)
  CMakeLists.txt:101 (rosidl_generate_interfaces)
`

## To Reproduce
** Steps to reproduce the behavior, e.g.
1. Download Android studio
2. Download Android NDK
3. Add .bashrc
`export ANDROID_HOEM=~/Android/Sdk
export PATH=$PATH:$ANDROID_HOEM/tools:$ANDROID_HOEM/platform-tool
export ANDROID_NDK=~/Android/ndk-r25c`
4. `mkdir -p $HOME/ros2_android_ws/src
cd $HOME/ros2_android_ws
curl https://raw.githubusercontent.com/pdl0x0lbq/ros2-humble-for-android/main/ros2_java_android.repos | vcs import src
`
5. `export PYTHON3_EXEC="$( which python3 )"
export PYTHON3_LIBRARY="$( ${PYTHON3_EXEC} -c 'import os.path; from distutils import sysconfig; print(os.path.realpath(os.path.join(sysconfig.get_config_var("LIBPL"), sysconfig.get_config_var("LDLIBRARY"))))' )"
export PYTHON3_INCLUDE_DIR="$( ${PYTHON3_EXEC} -c 'from distutils import sysconfig; print(sysconfig.get_config_var("INCLUDEPY"))' )"
export ANDROID_ABI=arm64-v8a
export ANDROID_NATIVE_API_LEVEL=android-29
export ANDROID_TOOLCHAIN_NAME=aarch64-linux-android-clang`
6. `colcon build \
 --packages-ignore cyclonedds rcl_logging_log4cxx rcl_logging_spdlog rosidl_generator_py rclandroid ros2_talker_android ros2_listener_android \ 
 --cmake-args \ 
 -DPYTHON_EXECUTABLE=${PYTHON3_EXEC} \ 
 -DPYTHON_LIBRARY=${PYTHON3_LIBRARY} \ 
 -DPYTHON_INCLUDE_DIR=${PYTHON3_INCLUDE_DIR} \
 -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK}/build/cmake/android.toolchain.cmake \ 
 -DANDROID=ON \ 
 -DANDROID_FUNCTION_LEVEL_LINKING=OFF \ 
 -DANDROID_NATIVE_API_LEVEL=${ANDROID_NATIVE_API_LEVEL} \ 
 -DANDROID_TOOLCHAIN_NAME=${ANDROID_TOOLCHAIN_NAME} \ 
 -DANDROID_STL=c++_shared \
 -DANDROID_ABI=${ANDROID_ABI} \ 
 -DANDROID_NDK=${ANDROID_NDK} \ 
 -DTHIRDPARTY=ON \ 
 -DCOMPILE_EXAMPLES=OFF \ 
 -DCMAKE_FIND_ROOT_PATH="${PWD}/install" \ 
 -DBUILD_TESTING=OFF \ 
 -DRCL_LOGGING_IMPLEMENTATION=rcl_logging_noop \ 
 -DTHIRDPARTY_android-ifaddrs=FORCE \ 
 -DTRACETOOLS_DISABLED=ON`

## System (please complete the following information)
 - OS: Ubuntu 22.04
 - ROS 2 Distro: humble
 - repos:https://raw.githubusercontent.com/pdl0x0lbq/ros2-humble-for-android/main/ros2_java_android.repos
*

**Comment by clalancette** [comment]
Android isn't one of our supported platforms, so we don't regularly test on it.  If you find a solution, please feel free to open a pull request and we'll be happy to review it.

**Comment by pdl0x0lbq** [comment]
> Android isn't one of our supported platforms, so we don't regularly test on it. If you find a solution, please feel free to open a pull request and we'll be happy to review it.

I solved it.
The problem is that the space in my compilation command is a carriage return.
