### ISSUE TITLE
Quesion of behavior: "0ms" publish interval, what should it do?

### ISSUE THREAD

**Issue by emersonknapp** [ros-tooling/libstatistics_collector#26]
## Description

When I specify 0ms as the publish_period, on my system it is publishing at ~2600Hz, which is probably as fast as it can go. Is this the intended behavior, or should 0 be an error, or should it mean the same as "disable"?

**Comment by dabonnie** [comment]
There's no validation here: https://github.com/ros2/rclcpp/pull/1072/files#diff-b6e9fd9f9a3fb6d2ff93b0f2a77983d4R100. We should file against `rclcpp`.

**Comment by emersonknapp** [comment]
Closing in favor of https://github.com/ros2/rclcpp/issues/1147
