### ISSUE TITLE
Build failure on Windows

### ISSUE THREAD

**Issue by rotu** [ros-tooling/libstatistics_collector#53]
## Description
I'm experiencing a build failure on Github CI Windows.

### Expected Behavior
libstatistics_collector builds cleanly

### Actual Behavior
The build fails with what looks like two paths being munged together:
```
Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(333,5): error MSB3491: Could not write lines to file "libstatistics_collector_test_msgs__rosidl_typesupport_introspection_cpp.dir\Release\libstati.25E7F2CC.tlog\libstatistics_collector_test_msgs__rosidl_typesupport_introspection_cpp.lastbuildstate". Could not find a part of the path 'D:\a\colcon-cmake\colcon-cmake\ros_ws\build\libstatistics_collector\libstatistics_collector_test_msgs__rosidl_typesupport_introspection_cpp.dir\Release\libstati.25E7F2CC.tlog\libstatistics_collector_test_msgs__rosidl_typesupport_introspection_cpp.lastbuildstate'. [D:\a\colcon-cmake\colcon-cmake\ros_ws\build\libstatistics_collector\libstatistics_collector_test_msgs__rosidl_typesupport_introspection_cpp.vcxproj]
2020-08-25T22:49:00.2052537Z ---Failed   <<< libstatistics_collector	[ Exited with code 1 ]
```
full logs:
https://github.com/rotu/colcon-cmake/runs/1028796089?check_suite_focus=true#step:15:13949

## To Reproduce
Run a github workflow like: https://github.com/rotu/colcon-cmake/actions/runs/224396277/workflow

## System (please complete the following information)
 - OS: Windows 10
 - ROS 2 Distro: Foxy

**Comment by clalancette** [comment]
The logs here have expired, and we haven't seen this elsewhere.  I'm going to close this one out, but of course feel free to reopen if you see this again.
