### ISSUE TITLE
New rolling release?

### ISSUE THREAD

**Issue by wjwwood** [ros-tooling/libstatistics_collector#91]
We're preparing to fork rolling into galactic and we noticed that there are changes on the default branch that have not been released: https://github.com/ros-tooling/libstatistics_collector/compare/1.0.1...master

(I don't know how to @ the ros-tooling wg, hopefully someone is watching) @`<maintainers>` do any of you have time to figure out whether or not a release is needed and if so do it? If you think it needs a release but do not have time we can try to do it for you.

**Comment by emersonknapp** [comment]
@ros-tooling/approvers list is probably a good go-to :) - I'll take this on, thanks for the ping!

**Comment by emersonknapp** [comment]
https://github.com/ros/rosdistro/pull/28750
